version: '3'
services:
  sync:
    image: waisbrot/wait
    depends_on:
      - postgres
      - swagger-validator
      - webhookd
    environment:
      TARGETS: "postgres:5432 webhookd:9300 swagger-validator:8080"
      TIMEOUT: "${INTEGRATION_TEST_TIMEOUT}"

  postgres:
    image: wazopbx/wazo-webhookd-db
    expose:
      - "5432"

  webhookd:
    image: "wazo-webhookd-test"
    environment:
      XIVO_UUID: "cd030e68-ace9-4ad4-bc4e-13c8dec67898"
    volumes:
      - "../../..:/usr/src/wazo-webhookd"
      - "./etc/wazo-webhookd:/etc/wazo-webhookd"
    ports:
      - "9300"

  swagger-validator:
    image: swaggerapi/swagger-validator
    ports:
      - "8080"
