sync:
  image: n3llyb0y/wait
  links:
    - webhookd
    - swagger-validator
  environment:
    PORTS: "9300 8080"
    TIMEOUT: "${INTEGRATION_TEST_TIMEOUT}"

webhookd:
  image: "wazo-webhookd-test"
  environment:
    - XIVO_UUID=cd030e68-ace9-4ad4-bc4e-13c8dec67898
  volumes:
    - "../../..:/usr/src/wazo-webhookd"
  ports:
    - "9300"

swagger-validator:
  image: swaggerapi/swagger-validator
  ports:
    - "8080"
  links:
    - webhookd
