version: '3'
services:
  sync:
    image: waisbrot/wait
    depends_on:
      - postgres
    environment:
      TARGETS: "postgres:5432"

  postgres:
    image: wazopbx/wazo-webhookd-db
    ports:
      - "5432"
